model: "mlx-community/Qwen3-4B-Instruct-2507-4bit"
train: true
fine_tune_type: lora
optimizer: adamw

mask_prompt: true

data: "data"
seed: 0

num_layers: 8

batch_size: 2
iters: 940
learning_rate: 2.0e-5

steps_per_report: 50
steps_per_eval: 300
val_batches: 10
save_every: 300

adapter_path: "train/adapters"
max_seq_length: 1536
grad_checkpoint: true

lora_parameters:
  rank: 16
  scale: 16.0
  dropout: 0.05
